#!/bin/bash
#SBATCH -J bl
#SBATCH -n 1
#SBATCH -p normal
#SBATCH -o bl.o%j
#SBATCH -e bl.e%j
#SBATCH -t 04:00:00
#SBATCH -A mega2014

module load launcher





export LAUNCHER_PLUGIN_DIR=$LAUNCHER_DIR/plugins
export LAUNCHER_RMI=SLURM
export LAUNCHER_JOB_FILE=bl248

$LAUNCHER_DIR/paramrun
