#!/bin/bash
#SBATCH -J getgo
#SBATCH -n 1
#SBATCH -p development
#SBATCH -o getgo.o%j
#SBATCH -e getgo.e%j
#SBATCH -t 1:00:00
#SBATCH -A mega2014

module load launcher





export LAUNCHER_PLUGIN_DIR=$LAUNCHER_DIR/plugins
export LAUNCHER_RMI=SLURM
export LAUNCHER_JOB_FILE=getgo

$LAUNCHER_DIR/paramrun
